name: 60-minute-cron
on:
  schedule:
    - cron: "37 */1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://sprak.karl.run/api/poll-post?posts=5'
