name: nightly-cron
on:
  schedule:
    - cron: "13 04 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://sprak.karl.run/api/poll-page'
